//! lshape exporter for [schema-bridge](https://crates.io/crates/schema-bridge).
//!
//! Turns the schema-bridge `Schema` IR into [lshape](https://github.com/ynishi/lshape)
//! type definitions — a Lua module built from `T.shape` / `T.array_of` /
//! `T.one_of` combinators that can be loaded and used with `lshape.check.check`.
//!
//! ```rust
//! use schema_bridge_core::{Field, Schema};
//! use schema_bridge_lshape::generate_lshape_file;
//!
//! let user = Schema::Object(vec![
//!     Field::new("name", Schema::String),
//!     Field::optional("email", Schema::String),
//! ]);
//! let lua_src = generate_lshape_file(&[("User", user)]).unwrap();
//! assert!(lua_src.contains("M.User = T.shape({"));
//! ```
//!
//! # lshape version requirement
//!
//! Generated modules use `T.integer` / `T.tuple` / the bounds combinators
//! (`:min` / `:max` / `:min_len` / `:max_len`), which require
//! **lshape 0.3.0+** at load time (vendored by `mlua-lshape 0.3+`).
//!
//! Semantic note: lshape's `T.integer` is the portable whole-number check
//! (`v % 1 == 0`), so `2.0` passes; Rust-side integer *range* (e.g. `u8`)
//! is not carried into the schema.

use schema_bridge_core::{Field, Schema};

/// Error produced while mapping a `Schema` to lshape source text.
#[derive(Debug, Clone, PartialEq)]
pub enum LshapeError {
    /// `Schema::Null` outside of a `Union` — lshape has no standalone nil
    /// type. Nullability is expressed by folding `Union([T, Null])` into
    /// `T:is_optional()`.
    StandaloneNull { path: String },
    /// `Schema::Union` whose only variant is `Null` (or which is empty).
    EmptyUnion { path: String },
    /// `Schema::Tuple` with no elements — `T.tuple` requires at least one
    /// item (unreachable via `#[derive(SchemaBridge)]`, which covers 1-6
    /// element tuples only).
    EmptyTuple { path: String },
}

impl std::fmt::Display for LshapeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LshapeError::StandaloneNull { path } => write!(
                f,
                "schema at `{path}` is a standalone Null — lshape has no nil type; \
                 wrap it in Option<T> / a Union with a non-null variant"
            ),
            LshapeError::EmptyUnion { path } => write!(
                f,
                "union at `{path}` has no non-null variant to map to lshape"
            ),
            LshapeError::EmptyTuple { path } => write!(
                f,
                "tuple at `{path}` has no elements — lshape T.tuple requires at least one item"
            ),
        }
    }
}

impl std::error::Error for LshapeError {}

/// Error produced by [`export_to_lua_file`].
#[derive(Debug)]
pub enum ExportError {
    Map(LshapeError),
    Io(std::io::Error),
}

impl std::fmt::Display for ExportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ExportError::Map(e) => write!(f, "{e}"),
            ExportError::Io(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for ExportError {}

impl From<LshapeError> for ExportError {
    fn from(e: LshapeError) -> Self {
        ExportError::Map(e)
    }
}

impl From<std::io::Error> for ExportError {
    fn from(e: std::io::Error) -> Self {
        ExportError::Io(e)
    }
}

const INDENT: &str = "    ";

/// Convert a single `Schema` into an lshape expression such as
/// `T.shape({ name = T.string })`.
pub fn schema_to_lshape(schema: &Schema) -> Result<String, LshapeError> {
    expr(schema, 0, "$")
}

/// Generate a complete Lua module defining one lshape schema per entry.
///
/// The module requires `lshape` (works out of the box under
/// [`mlua-lshape`](https://crates.io/crates/mlua-lshape)'s `install`, or any
/// Lua environment where `require("lshape")` resolves) and returns a table
/// with one key per exported type name.
pub fn generate_lshape_file(types: &[(&str, Schema)]) -> Result<String, LshapeError> {
    let mut out = String::new();
    out.push_str("-- This file is auto-generated by schema-bridge-lshape. Do not edit.\n");
    out.push_str("local T = require(\"lshape\").t\n\nlocal M = {}\n\n");
    for (name, schema) in types {
        let body = expr(schema, 0, name)?;
        out.push_str(&format!("M.{name} = {body}\n\n"));
    }
    out.push_str("return M\n");
    Ok(out)
}

/// Generate the lshape module for `types` and write it to `path`.
pub fn export_to_lua_file(types: &[(&str, Schema)], path: &str) -> Result<(), ExportError> {
    let content = generate_lshape_file(types)?;
    std::fs::write(path, content)?;
    Ok(())
}

/// Export types (anything deriving `SchemaBridge`) to an lshape Lua module.
///
/// ```ignore
/// export_lshape_types!("types.lua", User, Point)?;
/// ```
#[macro_export]
macro_rules! export_lshape_types {
    ($path:expr, $($name:ident),+ $(,)?) => {{
        let types = vec![
            $((stringify!($name), $name::to_schema()),)+
        ];
        $crate::export_to_lua_file(&types, $path)
    }};
}

fn expr(schema: &Schema, depth: usize, path: &str) -> Result<String, LshapeError> {
    match schema {
        Schema::String => Ok("T.string".to_string()),
        Schema::Number => Ok("T.number".to_string()),
        Schema::Integer => Ok("T.integer".to_string()),
        Schema::Boolean => Ok("T.boolean".to_string()),
        Schema::Any => Ok("T.any".to_string()),
        Schema::Null => Err(LshapeError::StandaloneNull {
            path: path.to_string(),
        }),
        Schema::Array(inner) => {
            let inner = expr(inner, depth, &format!("{path}[]"))?;
            Ok(format!("T.array_of({inner})"))
        }
        Schema::Record { key, value } => {
            let key = expr(key, depth, &format!("{path}<key>"))?;
            let value = expr(value, depth, &format!("{path}<value>"))?;
            Ok(format!("T.map_of({key}, {value})"))
        }
        Schema::Enum(values) => Ok(one_of_expr(values)),
        Schema::Union(variants) => union_expr(variants, depth, path),
        Schema::Tuple(items) => {
            if items.is_empty() {
                return Err(LshapeError::EmptyTuple {
                    path: path.to_string(),
                });
            }
            let exprs = items
                .iter()
                .enumerate()
                .map(|(i, s)| expr(s, depth, &format!("{path}[{i}]")))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(format!("T.tuple({{ {} }})", exprs.join(", ")))
        }
        Schema::Ref(name) => Ok(format!("T.ref({})", lua_string(name))),
        Schema::Object(fields) => shape_expr(fields, depth, path),
    }
}

/// `Union([T, Null])` folds to `T:is_optional()`; unions of two or more
/// non-null variants become `T.any_of({...})`.
fn union_expr(variants: &[Schema], depth: usize, path: &str) -> Result<String, LshapeError> {
    let non_null: Vec<&Schema> = variants.iter().filter(|v| **v != Schema::Null).collect();
    let nullable = non_null.len() != variants.len();
    let base = match non_null.len() {
        0 => {
            return Err(LshapeError::EmptyUnion {
                path: path.to_string(),
            })
        }
        1 => expr(non_null[0], depth, path)?,
        _ => {
            let exprs = non_null
                .iter()
                .enumerate()
                .map(|(i, v)| expr(v, depth, &format!("{path}|{i}")))
                .collect::<Result<Vec<_>, _>>()?;
            format!("T.any_of({{ {} }})", exprs.join(", "))
        }
    };
    if nullable {
        Ok(format!("{base}:is_optional()"))
    } else {
        Ok(base)
    }
}

fn shape_expr(fields: &[Field], depth: usize, path: &str) -> Result<String, LshapeError> {
    let field_indent = INDENT.repeat(depth + 1);
    let close_indent = INDENT.repeat(depth);
    let mut out = String::from("T.shape({\n");
    for field in fields {
        let field_path = format!("{path}.{}", field.name);
        let mut value = if let Some(one_of) = &field.constraints.one_of {
            one_of_expr(one_of)
        } else {
            expr(&field.schema, depth + 1, &field_path)?
        };
        value.push_str(&bounds_suffix(field));
        if !field.required && !value.ends_with(":is_optional()") {
            value.push_str(":is_optional()");
        }
        out.push_str(&format!(
            "{field_indent}{} = {value},\n",
            lua_key(&field.name)
        ));
    }
    out.push_str(&format!("{close_indent}}})"));
    Ok(out)
}

fn one_of_expr(values: &[String]) -> String {
    let quoted: Vec<String> = values.iter().map(|v| lua_string(v)).collect();
    format!("T.one_of({{ {} }})", quoted.join(", "))
}

/// Numeric / length constraints map to lshape's bounds combinators
/// (lshape 0.3+): chained calls merge into a single `bounded` wrapper and
/// are enforced at check time.
fn bounds_suffix(field: &Field) -> String {
    let c = &field.constraints;
    let mut out = String::new();
    if let Some(min) = c.min {
        out.push_str(&format!(":min({min})"));
    }
    if let Some(max) = c.max {
        out.push_str(&format!(":max({max})"));
    }
    if let Some(min_len) = c.min_len {
        out.push_str(&format!(":min_len({min_len})"));
    }
    if let Some(max_len) = c.max_len {
        out.push_str(&format!(":max_len({max_len})"));
    }
    out
}

const LUA_RESERVED: &[&str] = &[
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in",
    "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
];

fn lua_key(name: &str) -> String {
    let is_identifier = !name.is_empty()
        && !name.chars().next().unwrap().is_ascii_digit()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !LUA_RESERVED.contains(&name);
    if is_identifier {
        name.to_string()
    } else {
        format!("[{}]", lua_string(name))
    }
}

fn lua_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\{}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use schema_bridge_core::Constraints;

    fn field_with(name: &str, schema: Schema, constraints: Constraints) -> Field {
        Field {
            name: name.into(),
            schema,
            required: true,
            constraints,
        }
    }

    #[test]
    fn primitives() {
        assert_eq!(schema_to_lshape(&Schema::String).unwrap(), "T.string");
        assert_eq!(schema_to_lshape(&Schema::Number).unwrap(), "T.number");
        assert_eq!(schema_to_lshape(&Schema::Boolean).unwrap(), "T.boolean");
        assert_eq!(schema_to_lshape(&Schema::Any).unwrap(), "T.any");
    }

    #[test]
    fn integer_maps_to_t_integer() {
        assert_eq!(schema_to_lshape(&Schema::Integer).unwrap(), "T.integer");
    }

    #[test]
    fn standalone_null_is_an_error() {
        assert_eq!(
            schema_to_lshape(&Schema::Null),
            Err(LshapeError::StandaloneNull { path: "$".into() })
        );
    }

    #[test]
    fn array_and_record() {
        assert_eq!(
            schema_to_lshape(&Schema::Array(Box::new(Schema::String))).unwrap(),
            "T.array_of(T.string)"
        );
        let record = Schema::Record {
            key: Box::new(Schema::String),
            value: Box::new(Schema::Integer),
        };
        assert_eq!(
            schema_to_lshape(&record).unwrap(),
            "T.map_of(T.string, T.integer)"
        );
    }

    #[test]
    fn enum_maps_to_one_of() {
        let schema = Schema::Enum(vec!["active".into(), "inactive".into()]);
        assert_eq!(
            schema_to_lshape(&schema).unwrap(),
            r#"T.one_of({ "active", "inactive" })"#
        );
    }

    #[test]
    fn union_with_null_folds_to_optional() {
        // Option<String>::to_schema() == Union([String, Null])
        let schema = Schema::Union(vec![Schema::String, Schema::Null]);
        assert_eq!(schema_to_lshape(&schema).unwrap(), "T.string:is_optional()");
    }

    #[test]
    fn union_without_null_maps_to_any_of() {
        let schema = Schema::Union(vec![Schema::String, Schema::Number]);
        assert_eq!(
            schema_to_lshape(&schema).unwrap(),
            "T.any_of({ T.string, T.number })"
        );
    }

    #[test]
    fn union_with_null_and_two_variants() {
        let schema = Schema::Union(vec![Schema::String, Schema::Number, Schema::Null]);
        assert_eq!(
            schema_to_lshape(&schema).unwrap(),
            "T.any_of({ T.string, T.number }):is_optional()"
        );
    }

    #[test]
    fn union_of_only_null_is_an_error() {
        assert_eq!(
            schema_to_lshape(&Schema::Union(vec![Schema::Null])),
            Err(LshapeError::EmptyUnion { path: "$".into() })
        );
    }

    #[test]
    fn tuple_maps_to_t_tuple() {
        let schema = Schema::Tuple(vec![Schema::String, Schema::Integer]);
        assert_eq!(
            schema_to_lshape(&schema).unwrap(),
            "T.tuple({ T.string, T.integer })"
        );
    }

    #[test]
    fn empty_tuple_is_an_error() {
        assert_eq!(
            schema_to_lshape(&Schema::Tuple(vec![])),
            Err(LshapeError::EmptyTuple { path: "$".into() })
        );
    }

    #[test]
    fn ref_maps_to_t_ref() {
        assert_eq!(
            schema_to_lshape(&Schema::Ref("Point".into())).unwrap(),
            r#"T.ref("Point")"#
        );
    }

    #[test]
    fn object_with_optional_field() {
        let schema = Schema::Object(vec![
            Field::new("name", Schema::String),
            Field::optional("email", Schema::String),
        ]);
        let expected = "T.shape({\n    name = T.string,\n    email = T.string:is_optional(),\n})";
        assert_eq!(schema_to_lshape(&schema).unwrap(), expected);
    }

    #[test]
    fn optional_field_with_nullable_schema_does_not_double_wrap() {
        // #[derive] with Option<T> yields required=false AND Union([T, Null]).
        let schema = Schema::Object(vec![Field {
            name: "email".into(),
            schema: Schema::Union(vec![Schema::String, Schema::Null]),
            required: false,
            constraints: Constraints::default(),
        }]);
        let out = schema_to_lshape(&schema).unwrap();
        assert_eq!(out.matches(":is_optional()").count(), 1);
    }

    #[test]
    fn field_constraints_become_bounds() {
        let schema = Schema::Object(vec![field_with(
            "age",
            Schema::Integer,
            Constraints {
                min: Some(0.0),
                max: Some(150.0),
                ..Default::default()
            },
        )]);
        let expected = "T.shape({\n    age = T.integer:min(0):max(150),\n})";
        assert_eq!(schema_to_lshape(&schema).unwrap(), expected);
    }

    #[test]
    fn field_length_constraints_become_len_bounds() {
        let schema = Schema::Object(vec![field_with(
            "name",
            Schema::String,
            Constraints {
                min_len: Some(1),
                max_len: Some(64),
                ..Default::default()
            },
        )]);
        let expected = "T.shape({\n    name = T.string:min_len(1):max_len(64),\n})";
        assert_eq!(schema_to_lshape(&schema).unwrap(), expected);
    }

    #[test]
    fn field_one_of_constraint_overrides_base_type() {
        let schema = Schema::Object(vec![field_with(
            "status",
            Schema::String,
            Constraints {
                one_of: Some(vec!["on".into(), "off".into()]),
                ..Default::default()
            },
        )]);
        let expected = "T.shape({\n    status = T.one_of({ \"on\", \"off\" }),\n})";
        assert_eq!(schema_to_lshape(&schema).unwrap(), expected);
    }

    #[test]
    fn nested_object_indents() {
        let schema = Schema::Object(vec![Field::new(
            "point",
            Schema::Object(vec![Field::new("x", Schema::Number)]),
        )]);
        let expected = "T.shape({\n    point = T.shape({\n        x = T.number,\n    }),\n})";
        assert_eq!(schema_to_lshape(&schema).unwrap(), expected);
    }

    #[test]
    fn non_identifier_and_reserved_keys_are_bracketed() {
        let schema = Schema::Object(vec![
            Field::new("valid_key", Schema::String),
            Field::new("kebab-case", Schema::String),
            Field::new("end", Schema::String),
        ]);
        let out = schema_to_lshape(&schema).unwrap();
        assert!(out.contains("    valid_key = T.string,"));
        assert!(out.contains("    [\"kebab-case\"] = T.string,"));
        assert!(out.contains("    [\"end\"] = T.string,"));
    }

    #[test]
    fn lua_string_escapes() {
        assert_eq!(lua_string(r#"a"b\c"#), r#""a\"b\\c""#);
        assert_eq!(lua_string("a\nb"), r#""a\nb""#);
    }

    #[test]
    fn error_path_points_at_field() {
        let schema = Schema::Object(vec![Field::new("bad", Schema::Null)]);
        assert_eq!(
            schema_to_lshape(&schema),
            Err(LshapeError::StandaloneNull {
                path: "$.bad".into()
            })
        );
    }

    #[test]
    fn generate_file_layout() {
        let types = vec![
            (
                "User",
                Schema::Object(vec![Field::new("name", Schema::String)]),
            ),
            ("Id", Schema::String),
        ];
        let out = generate_lshape_file(&types).unwrap();
        assert!(out
            .starts_with("-- This file is auto-generated by schema-bridge-lshape. Do not edit.\n"));
        assert!(out.contains("local T = require(\"lshape\").t\n"));
        assert!(out.contains("M.User = T.shape({\n    name = T.string,\n})\n"));
        assert!(out.contains("M.Id = T.string\n"));
        assert!(out.ends_with("return M\n"));
    }
}
